# Generated by Django 4.1.1 on 2024-11-04 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
    ]
