# Generated by Django 4.1.1 on 2024-10-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TapStatus',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
